'use client';

// import type { Metadata } from 'next';

import { inter } from '@/config/fonts';

import { useEffect, useState } from 'react';
import { ToastifyProvider } from '@/components/providers';
import { VerifyingCredentials } from '@/components/ui';
import './globals.css';
import { verifyTokenExpired } from '@/actions/auth';
import { useAuthStore } from '@/store/auth';

// export const metadata: Metadata = {
//   title: {
//     template: '%s - Shop | Store',
//     default: 'Home - Shop | Store',
//   },
//   description: 'Generated by create next app',
// };

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  const [isTokenValidating, setIsTokenValidating] = useState(true);

  const setIsAuth = useAuthStore((s) => s.setIsAuth);

  useEffect(() => {
    const handleTokenExpired = async () => {
      const { isTokenExpired } = await verifyTokenExpired();
      setIsAuth(!isTokenExpired);
      setIsTokenValidating(false);
    };

    handleTokenExpired();
  }, [setIsAuth]);

  return (
    // <html lang='en' className='dark'>
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        {isTokenValidating ? (
          <VerifyingCredentials />
        ) : (
          <ToastifyProvider>{children}</ToastifyProvider>
        )}
      </body>
    </html>
  );
}
