import type { Metadata } from 'next';

import { inter } from '@/config/fonts';

import './globals.css';
import { ToastifyProvider } from '@/components/providers';

export const metadata: Metadata = {
  title: {
    template: '%s - Shop | Store',
    default: 'Home - Shop | Store',
  },
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    // <html lang='en' className='dark'>
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <ToastifyProvider>{children}</ToastifyProvider>
      </body>
    </html>
  );
}
